config/routes.rb
Rails.application.routes.draw do
  get 'klasses/index'
  get 'klasses/show'
  get 'klasses/new'
  get 'klasses/create'
  get 'klasses/edit'
  get 'klasses/update'
  get 'klasses/destroy'
  resources :presentations
  resources :klasses do
    member do
      post :join
    end
  end
  resources :surveys
  resources :events
  resources :teachers
  resources :users
  resources :students
  resources :groups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'users#index'
  root to: 'sessions#login'

  get 'signup', to: 'sessions#signup'
  get 'login', to: 'sessions#login'
  get 'main', to: 'sessions#main'

  get '/logout', to: "sessions#logout", as: "logout"
  post "/", to: "sessions#create", via: :post
  post "/sessions", to: "sessions#create"
  post '/signup', to: 'sessions#login'

  get '/klasses/:id/join', to: 'users#joinClass'

end

app/models/presentation.rb
class Presentation < ApplicationRecord
  # TODO: teacher should assign presentation to GROUP or USER
  # belongs_to :event
  # Temperorily user
  belongs_to :group, optional: true
  belongs_to :student, optional: true
  has_many :surveys
  has_many :students, class_name: "User", through: :surveys
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: %i[ show edit update destroy ]

  # GET /presentations or /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1 or /presentations/1.json
  def show
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations or /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to presentation_url(@presentation), notice: "Presentation was successfully created." }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1 or /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to presentation_url(@presentation), notice: "Presentation was successfully updated." }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1 or /presentations/1.json
  def destroy
    @presentation.destroy

    respond_to do |format|
      format.html { redirect_to presentations_url, notice: "Presentation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presentation_params
      params.require(:presentation).permit(:title, :description, :student_id, :event_id)
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<%= form_with(model: presentation) do |form| %>
  <% if presentation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
        <% presentation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :current_user.name, disabled: true%>
  </div>


  <% user_group = Group.where(student_id: current_user).first %>



  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :user_group, disabled: true%>
  </div>

  <div>
    <%= form.label :event_id, style: "display: block" %>
    <%#= form.number_field :event_id %>
    <%= form.collection_select :event_id, Event.all, :id, :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/presentations/_present.html.erb
<div id="<%= dom_id presentation %>">
  <p>
    <strong>Title:</strong>
    <%= presentation.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= presentation.description %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= presentation.student_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= presentation.event_id %>
  </p>


  <% if presentation.surveys.present? %>
    <strong>Surveys related:</strong>
    <p> Avg_score: <%= presentation.surveys.map { |object| object.rating }.reduce(:+) / presentation.surveys.length%></p>
    <% surveys =  presentation.surveys%>
    <% positives = surveys.select{ |survey| survey.rating >= 5} %>
    <% negatives = surveys.select{ |survey| survey.rating < 5} %>
  <hr/>
    <p class="pos"> Positive comment(<%= positives.length%>): </p>
    <% positives.each do |survey| %>
      <p> rating: <%= survey.rating%></p>
      <p> comment:</p>
      <p> <%= link_to survey.comment, survey%></p>
    <% end %>
  <hr/>
  <p class="neg"> Negative comment(<%=negatives.length %>): </p>
    <% negatives.each do |survey| %>
      <p> rating: <%= survey.rating%></p>
      <p> comment:</p>
      <p> <%= link_to survey.comment, survey%></p>
    <% end %>
  </p>
    <%end %>
</div>

app/views/presentations/_presentation.html.erb
<div id="<%= dom_id presentation %>">
  <p>
    <strong>Title:</strong>
    <%= presentation.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= presentation.description %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= presentation.student_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= presentation.event_id %>
  </p>

  <p>
    <strong>Surveys related:</strong>
    <p> Avg_score: <%= presentation.surveys.map { |object| object.rating }.reduce(:+) / presentation.surveys.length%></p>
    <% surveys =  presentation.surveys%>
    <% positives = surveys.select{ |survey| survey.rating >= 5} %>
    <% negatives = surveys.select{ |survey| survey.rating < 5} %>
    <p> Positive comment(<%= positives.length%>): </p>
    <% positives.each do |survey| %>
      <p> rating: <%= survey.rating%></p>
      <p> comment:<%= link_to survey.comment, survey%></p>
    <% end %>
  <p> Negative comment(<%=negatives.length %>): </p>
    <% negatives.each do |survey| %>
      <p> rating: <%= survey.rating%></p>
      <p> comment:<%= link_to survey.comment, survey%></p>
    <% end %>
  </p>
</div>

app/views/presentations/_surveys.html.erb
<div id="<%=  %>">
  <p>
    <strong>Title:</strong>
    <%= presentation.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= presentation.description %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= presentation.student_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= presentation.event_id %>
  </p>

</div>

app/views/presentations/edit.html.erb
<h1>Editing presentation</h1>

<%= render "form", presentation: @presentation %>

<br>

<div>
  <p color="red">feature(TODO): </p>
  <%= link_to "Show the survey of the presentation", @presentation %> |

  <%= link_to "Show this presentation", @presentation %> |
  <%= link_to "Back to presentations", presentations_path %>
</div>

app/views/presentations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Presentations</h1>

<div id="presentations">
  <% @presentations.each do |presentation| %>
    <%= render presentation %>
    <p>
      <%= link_to "Show this presentation", presentation %>
    </p>
  <% end %>
</div>

<%= link_to "New presentation", new_presentation_path %>

app/views/presentations/new.html.erb
<h1>New presentation</h1>

<%= render "form", presentation: @presentation %>

<br>

<div>
  <%= link_to "Back to presentations", presentations_path %>
</div>

app/views/presentations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @presentation %>

<div>
  <%= link_to "Edit this presentation", edit_presentation_path(@presentation) %> |
  <%= link_to "Back to presentations", presentations_path %>

  <%= button_to "Destroy this presentation", @presentation, method: :delete %>
</div>