config/routes.rb
Rails.application.routes.draw do
  get 'klasses/index'
  get 'klasses/show'
  get 'klasses/new'
  get 'klasses/create'
  get 'klasses/edit'
  get 'klasses/update'
  get 'klasses/destroy'
  resources :presentations
  resources :klasses do
    member do
      post :join
    end
  end
  resources :surveys
  resources :events
  resources :teachers
  resources :users
  resources :students
  resources :groups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'users#index'
  root to: 'sessions#login'

  get 'signup', to: 'sessions#signup'
  get 'login', to: 'sessions#login'
  get 'main', to: 'sessions#main'

  get '/logout', to: "sessions#logout", as: "logout"
  post "/", to: "sessions#create", via: :post
  post "/sessions", to: "sessions#create"
  post '/signup', to: 'sessions#login'

  get '/klasses/:id/join', to: 'users#joinClass'

end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :class_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Class:</strong>
    <%= event.class_id %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>


  <%= form.hidden_field :class_id, value: params[:class_id] %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Class Name</h1>

<h2>Current Events</h2>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%# if current_user.type == "student"%>
  <h2>Submit Presentation For This Event:</h2>
  <%# <%= form_with(model: @presentation, url: klass_event_presentations_path(@klass, @event), method: :post) do |form| %>
    <%# <%= form.hidden_field :group_id, value: current_user.group_id %>
    <%# <%= form.label :title %> 
    <%# <%= form.text_field :title %> 
    <%# <%= form.label :description %> 
    <%# <%= form.text_area :description %> 
    <%# <%= form.label :file %> 
    <%# <%= form.file_field :file %> 
    <%# <%= form.submit "Submit" %> 
  <%# <% end %> 
<%# <% end %> 

<%# if current_user.type == "teacher"%>
  <h2>Create New Event:</h2>
  <%# link_to "Create Event", new_event_path(klass_id: klass.id) %>
<%# <% end %> 



<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<h1>Create New Event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>