config/routes.rb
Rails.application.routes.draw do
  get 'klasses/index'
  get 'klasses/show'
  get 'klasses/new'
  get 'klasses/create'
  get 'klasses/edit'
  get 'klasses/update'
  get 'klasses/destroy'
  resources :presentations
  resources :klasses do
    member do
      post :join
    end
  end
  resources :surveys
  resources :events
  resources :teachers
  resources :users
  resources :students
  resources :groups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'users#index'
  root to: 'sessions#login'

  get 'signup', to: 'sessions#signup'
  get 'login', to: 'sessions#login'
  get 'main', to: 'sessions#main'

  get '/logout', to: "sessions#logout", as: "logout"
  post "/", to: "sessions#create", via: :post
  post "/sessions", to: "sessions#create"
  post '/signup', to: 'sessions#login'

  get '/klasses/:id/join', to: 'users#joinClass'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :students, class_name: "User"
end

app/models/klass.rb
class Klass < ApplicationRecord
    belongs_to :teacher, class_name: "User"
    has_many :students, class_name: "User"
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  # TODO: teacher should assign presentation to GROUP or USER
  # belongs_to :event
  # Temperorily user
  belongs_to :group, optional: true
  belongs_to :student, optional: true
  has_many :surveys
  has_many :students, class_name: "User", through: :surveys
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :presentation
  belongs_to :student, class_name: "User"

  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 10,
    message: "Rating must be an integer between 1 and 10"
  }
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, uniqueness: { message: "This email address is already in use. Please choose a different one." }

  has_many :surveys, foreign_key: "student_id"
  has_many :presentations, through: :surveys

  # belongs_to :klass

  belongs_to :groups, class_name: "Group", optional: true
  validates :group, uniqueness: true, if: -> { groups.present? }

  # Include the has_secure_password method in the User model
  has_secure_password

  def teacher?
    self.character == 'teacher'
  end

  def student?
    self.character == 'student'
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]


  def joinClass
    @student = current_user
    @klass = @student.klass
    redirect_to @klass
  end

  
  def signup
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # If the user was successfully saved, redirect to the login page
      flash[:success] = "Successfully created user account, login!"
      redirect_to login_path
    else
      # Initialize a new user object if the save fails
      @user = User.new
      # Set the error message to display to the user
      flash.now[:danger] = 'That email is already in use. Please choose a different email.'
      # Render the signup form again
      render 'sessions/signup'
    end
  end



  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users or /users.json
 

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to main_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :name, :user_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_loginfo.html.erb
<br>
<div>
  <% if current_user.present? %>
    <strong> Hello </strong>
    <%= current_user.name %>
    <br>
    <%= link_to  "Back to main page", main_path%> |
    <%= link_to "Edit your account", edit_user_path(current_user) %> |
    <%= link_to "Log Out", logout_path, method: :delete %>
    <hr class ="line">
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<br>
<nav>
  <br>
  Navbar:
  <%= link_to "All Survey", surveys_url %> |
  <%= link_to "All Presentation", presentations_url %> |
  <%= link_to "All User", users_url %> |
  <%= link_to "All Class", klasses_url %> |
</nav>

<p style="color: green"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student rating system</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
  <%= render "layouts/loginfo" %>
    <img class="osulogo" src="assets/osulogo.png" alt="">
    <h1 style="font-size: 25px">Evaluation of Class Presentations</h1>
    <hr class="line">
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <hr class ="line">
  </body>
</html>